language: python
python:
  - '3.6'
env:
  - DJANGO="Django>=1.11,<1.12.0"
  - DJANGO="Django>=2.0,<2.1"
install:
  - pip install $DJANGO
  - pip install -r requirements.txt
script:
  - make flake8
  - make test
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
